version: '3'

services:

  sonarqube:
    container_name: sonarqube
    restart: always
    image: sonarqube:9.9.0-community
    depends_on:
      - sonar-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      app-network:

  sonar-db:
    container_name: sonar-db
    restart: always
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      app-network:

#  gitlab:
#    container_name: gitlab
#    image: 'gitlab/gitlab-ee:latest'
#    restart: always
#    hostname: 'gitlab.local'
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'http://gitlab.local'
#
#    volumes:
#      - 'gitlab_config:/etc/gitlab'
#      - 'gitlab_logs:/var/log/gitlab'
#      - 'gitlab_data:/var/opt/gitlab'
#    shm_size: '256m'
#    networks:
#      app-network:
##        ipv4_address: 172.16.238.11


networks:
  app-network:
    external:
      name: app-network


volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
#  gitlab_config:
#  gitlab_logs:
#  gitlab_data: